version: '3'
services:
  ### Postgres Configuration for Inventory
  db-inventory:
    container_name: db-inventory
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms_inventory
      POSTGRES_USER: ags
      POSTGRES_PASSWORD: root123
    ports:
      - 5431:5431
    expose:
      - 5431
    command: -p 5431
  ### MySQL Configuraton for Orders
  db_orders:
    container_name: db-orders
    image: mysql:8.0.33
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ms_orders
      MYSQL_USER: ags
      MYSQL_PASSWORD: root123
      MYSQL_ROOT_PASSWORD: root123
    ports:
      - 3306:3306
    expose:
      - 3306
  ### Postgres Configuration for Products
  db_products:
    container_name: db_products
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms_products
      POSTGRES_USER: ags
      POSTGRES_PASSWORD: root123
    ports:
      - 5432:5432
    expose:
      - 5432
